[package]
name = "fixed_width_derive"
version = "0.1.0"
authors = ["Tom King <twking7@gmail.com>"]
repository = "https://github.com/twking7/fixed_width/fixed_width_derive"
description = "Derive trait for use with the fixed_width crate."
license = "MIT"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4.6"
syn = { version = "0.14.2", features = ["extra-traits"] }
quote = "0.6.3"
fixed_width = { path = "../fixed_width" }

[dev-dependencies]
serde = "1.0"
serde_derive = "1.0"
